// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProto.proto

package com.github.xjs.protobuffdemo.nano;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgWeaponSkillDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameProto.MsgWeaponSkillData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 skillID = 1;</code>
     */
    int getSkillID();

    /**
     * <code>int32 curExp = 2;</code>
     */
    int getCurExp();

    /**
     * <code>int32 maxExp = 3;</code>
     */
    int getMaxExp();
  }
  /**
   * Protobuf type {@code GameProto.MsgWeaponSkillData}
   */
  public  static final class MsgWeaponSkillData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GameProto.MsgWeaponSkillData)
      MsgWeaponSkillDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgWeaponSkillData.newBuilder() to construct.
    private MsgWeaponSkillData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgWeaponSkillData() {
      skillID_ = 0;
      curExp_ = 0;
      maxExp_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgWeaponSkillData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              skillID_ = input.readInt32();
              break;
            }
            case 16: {

              curExp_ = input.readInt32();
              break;
            }
            case 24: {

              maxExp_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xjs.protobuffdemo.nano.MessageProto.internal_static_GameProto_MsgWeaponSkillData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xjs.protobuffdemo.nano.MessageProto.internal_static_GameProto_MsgWeaponSkillData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.class, com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.Builder.class);
    }

    public static final int SKILLID_FIELD_NUMBER = 1;
    private int skillID_;
    /**
     * <code>int32 skillID = 1;</code>
     */
    public int getSkillID() {
      return skillID_;
    }

    public static final int CUREXP_FIELD_NUMBER = 2;
    private int curExp_;
    /**
     * <code>int32 curExp = 2;</code>
     */
    public int getCurExp() {
      return curExp_;
    }

    public static final int MAXEXP_FIELD_NUMBER = 3;
    private int maxExp_;
    /**
     * <code>int32 maxExp = 3;</code>
     */
    public int getMaxExp() {
      return maxExp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (skillID_ != 0) {
        output.writeInt32(1, skillID_);
      }
      if (curExp_ != 0) {
        output.writeInt32(2, curExp_);
      }
      if (maxExp_ != 0) {
        output.writeInt32(3, maxExp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (skillID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, skillID_);
      }
      if (curExp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, curExp_);
      }
      if (maxExp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, maxExp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData)) {
        return super.equals(obj);
      }
      com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData other = (com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData) obj;

      boolean result = true;
      result = result && (getSkillID()
          == other.getSkillID());
      result = result && (getCurExp()
          == other.getCurExp());
      result = result && (getMaxExp()
          == other.getMaxExp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SKILLID_FIELD_NUMBER;
      hash = (53 * hash) + getSkillID();
      hash = (37 * hash) + CUREXP_FIELD_NUMBER;
      hash = (53 * hash) + getCurExp();
      hash = (37 * hash) + MAXEXP_FIELD_NUMBER;
      hash = (53 * hash) + getMaxExp();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameProto.MsgWeaponSkillData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameProto.MsgWeaponSkillData)
        com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.xjs.protobuffdemo.nano.MessageProto.internal_static_GameProto_MsgWeaponSkillData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.xjs.protobuffdemo.nano.MessageProto.internal_static_GameProto_MsgWeaponSkillData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.class, com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.Builder.class);
      }

      // Construct using com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        skillID_ = 0;

        curExp_ = 0;

        maxExp_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.xjs.protobuffdemo.nano.MessageProto.internal_static_GameProto_MsgWeaponSkillData_descriptor;
      }

      public com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData getDefaultInstanceForType() {
        return com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.getDefaultInstance();
      }

      public com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData build() {
        com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData buildPartial() {
        com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData result = new com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData(this);
        result.skillID_ = skillID_;
        result.curExp_ = curExp_;
        result.maxExp_ = maxExp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData) {
          return mergeFrom((com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData other) {
        if (other == com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.getDefaultInstance()) return this;
        if (other.getSkillID() != 0) {
          setSkillID(other.getSkillID());
        }
        if (other.getCurExp() != 0) {
          setCurExp(other.getCurExp());
        }
        if (other.getMaxExp() != 0) {
          setMaxExp(other.getMaxExp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int skillID_ ;
      /**
       * <code>int32 skillID = 1;</code>
       */
      public int getSkillID() {
        return skillID_;
      }
      /**
       * <code>int32 skillID = 1;</code>
       */
      public Builder setSkillID(int value) {
        
        skillID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 skillID = 1;</code>
       */
      public Builder clearSkillID() {
        
        skillID_ = 0;
        onChanged();
        return this;
      }

      private int curExp_ ;
      /**
       * <code>int32 curExp = 2;</code>
       */
      public int getCurExp() {
        return curExp_;
      }
      /**
       * <code>int32 curExp = 2;</code>
       */
      public Builder setCurExp(int value) {
        
        curExp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 curExp = 2;</code>
       */
      public Builder clearCurExp() {
        
        curExp_ = 0;
        onChanged();
        return this;
      }

      private int maxExp_ ;
      /**
       * <code>int32 maxExp = 3;</code>
       */
      public int getMaxExp() {
        return maxExp_;
      }
      /**
       * <code>int32 maxExp = 3;</code>
       */
      public Builder setMaxExp(int value) {
        
        maxExp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 maxExp = 3;</code>
       */
      public Builder clearMaxExp() {
        
        maxExp_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GameProto.MsgWeaponSkillData)
    }

    // @@protoc_insertion_point(class_scope:GameProto.MsgWeaponSkillData)
    private static final com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData();
    }

    public static com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgWeaponSkillData>
        PARSER = new com.google.protobuf.AbstractParser<MsgWeaponSkillData>() {
      public MsgWeaponSkillData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgWeaponSkillData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgWeaponSkillData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgWeaponSkillData> getParserForType() {
      return PARSER;
    }

    public com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GameProto_MsgWeaponSkillData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GameProto_MsgWeaponSkillData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MessageProto.proto\022\tGameProto\032\017BasePro" +
      "to.proto\"E\n\022MsgWeaponSkillData\022\017\n\007skillI" +
      "D\030\001 \001(\005\022\016\n\006curExp\030\002 \001(\005\022\016\n\006maxExp\030\003 \001(\005B" +
      "1\n!com.github.xjs.protobuffdemo.nanoB\014Me" +
      "ssageProtoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.xjs.protobuffdemo.nano.BaseProto.getDescriptor(),
        }, assigner);
    internal_static_GameProto_MsgWeaponSkillData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameProto_MsgWeaponSkillData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GameProto_MsgWeaponSkillData_descriptor,
        new java.lang.String[] { "SkillID", "CurExp", "MaxExp", });
    com.github.xjs.protobuffdemo.nano.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
