// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.github.xjs.protobuffdemo.nano;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:person.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *由于repeated关键字修饰，这个属性将会生成一个集合
     * </pre>
     *
     * <code>repeated string position = 7;</code>
     */
    java.util.List<java.lang.String>
        getPositionList();
    /**
     * <pre>
     *由于repeated关键字修饰，这个属性将会生成一个集合
     * </pre>
     *
     * <code>repeated string position = 7;</code>
     */
    int getPositionCount();
    /**
     * <pre>
     *由于repeated关键字修饰，这个属性将会生成一个集合
     * </pre>
     *
     * <code>repeated string position = 7;</code>
     */
    java.lang.String getPosition(int index);
    /**
     * <pre>
     *由于repeated关键字修饰，这个属性将会生成一个集合
     * </pre>
     *
     * <code>repeated string position = 7;</code>
     */
    com.google.protobuf.ByteString
        getPositionBytes(int index);

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>int32 id = 3;</code>
     */
    int getId();

    /**
     * <code>string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.person.Person.china nation = 5;</code>
     */
    boolean hasNation();
    /**
     * <code>.person.Person.china nation = 5;</code>
     */
    com.github.xjs.protobuffdemo.nano.PersonProto.Person.china getNation();
    /**
     * <code>.person.Person.china nation = 5;</code>
     */
    com.github.xjs.protobuffdemo.nano.PersonProto.Person.chinaOrBuilder getNationOrBuilder();

    /**
     * <pre>
     *map类型的key不能是枚举类型(enum)
     * </pre>
     *
     * <code>map&lt;string, string&gt; address = 8;</code>
     */
    int getAddressCount();
    /**
     * <pre>
     *map类型的key不能是枚举类型(enum)
     * </pre>
     *
     * <code>map&lt;string, string&gt; address = 8;</code>
     */
    boolean containsAddress(
        java.lang.String key);
    /**
     * Use {@link #getAddressMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAddress();
    /**
     * <pre>
     *map类型的key不能是枚举类型(enum)
     * </pre>
     *
     * <code>map&lt;string, string&gt; address = 8;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAddressMap();
    /**
     * <pre>
     *map类型的key不能是枚举类型(enum)
     * </pre>
     *
     * <code>map&lt;string, string&gt; address = 8;</code>
     */

    java.lang.String getAddressOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     *map类型的key不能是枚举类型(enum)
     * </pre>
     *
     * <code>map&lt;string, string&gt; address = 8;</code>
     */

    java.lang.String getAddressOrThrow(
        java.lang.String key);

    /**
     * <code>.baseproto.MsgBaseData baseProto = 6;</code>
     */
    boolean hasBaseProto();
    /**
     * <code>.baseproto.MsgBaseData baseProto = 6;</code>
     */
    com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData getBaseProto();
    /**
     * <code>.baseproto.MsgBaseData baseProto = 6;</code>
     */
    com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseDataOrBuilder getBaseProtoOrBuilder();
  }
  /**
   * <pre>
   *option java_multiple_files = true;
   *option java_generic_services = true;
   *option optimize_for = SPEED;
   * </pre>
   *
   * Protobuf type {@code person.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:person.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      position_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      name_ = "";
      age_ = 0;
      id_ = 0;
      email_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 24: {

              id_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 42: {
              com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.Builder subBuilder = null;
              if (nation_ != null) {
                subBuilder = nation_.toBuilder();
              }
              nation_ = input.readMessage(com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(nation_);
                nation_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.Builder subBuilder = null;
              if (baseProto_ != null) {
                subBuilder = baseProto_.toBuilder();
              }
              baseProto_ = input.readMessage(com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(baseProto_);
                baseProto_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                position_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              position_.add(s);
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                address_ = com.google.protobuf.MapField.newMapField(
                    AddressDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              address__ = input.readMessage(
                  AddressDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              address_.getMutableMap().put(
                  address__.getKey(), address__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          position_ = position_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetAddress();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xjs.protobuffdemo.nano.PersonProto.Person.class, com.github.xjs.protobuffdemo.nano.PersonProto.Person.Builder.class);
    }

    /**
     * <pre>
     *枚举类型
     * </pre>
     *
     * Protobuf enum {@code person.Person.PhoneType}
     */
    public enum PhoneType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>HOME = 0;</code>
       */
      HOME(0),
      /**
       * <code>MOBILE = 1;</code>
       */
      MOBILE(1),
      /**
       * <pre>
       *实际上只是为同一个值增加了一个别名，生成代码后的格式是work = company
       * </pre>
       *
       * <code>WORK = 2;</code>
       */
      WORK(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>COMPANY = 2;</code>
       */
      public static final PhoneType COMPANY = WORK;
      /**
       * <code>HOME = 0;</code>
       */
      public static final int HOME_VALUE = 0;
      /**
       * <code>MOBILE = 1;</code>
       */
      public static final int MOBILE_VALUE = 1;
      /**
       * <pre>
       *实际上只是为同一个值增加了一个别名，生成代码后的格式是work = company
       * </pre>
       *
       * <code>WORK = 2;</code>
       */
      public static final int WORK_VALUE = 2;
      /**
       * <code>COMPANY = 2;</code>
       */
      public static final int COMPANY_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PhoneType valueOf(int value) {
        return forNumber(value);
      }

      public static PhoneType forNumber(int value) {
        switch (value) {
          case 0: return HOME;
          case 1: return MOBILE;
          case 2: return WORK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PhoneType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
              public PhoneType findValueByNumber(int number) {
                return PhoneType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.github.xjs.protobuffdemo.nano.PersonProto.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final PhoneType[] VALUES = {
        HOME, MOBILE, WORK, COMPANY, 
      };

      public static PhoneType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PhoneType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:person.Person.PhoneType)
    }

    public interface chinaOrBuilder extends
        // @@protoc_insertion_point(interface_extends:person.Person.china)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 area = 1;</code>
       */
      long getArea();

      /**
       * <code>string money = 2;</code>
       */
      java.lang.String getMoney();
      /**
       * <code>string money = 2;</code>
       */
      com.google.protobuf.ByteString
          getMoneyBytes();

      /**
       * <code>.person.Person.PhoneType type = 3;</code>
       */
      int getTypeValue();
      /**
       * <code>.person.Person.PhoneType type = 3;</code>
       */
      com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType getType();
    }
    /**
     * Protobuf type {@code person.Person.china}
     */
    public  static final class china extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:person.Person.china)
        chinaOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use china.newBuilder() to construct.
      private china(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private china() {
        area_ = 0L;
        money_ = "";
        type_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private china(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                area_ = input.readInt64();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                money_ = s;
                break;
              }
              case 24: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_china_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_china_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.class, com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.Builder.class);
      }

      public static final int AREA_FIELD_NUMBER = 1;
      private long area_;
      /**
       * <code>int64 area = 1;</code>
       */
      public long getArea() {
        return area_;
      }

      public static final int MONEY_FIELD_NUMBER = 2;
      private volatile java.lang.Object money_;
      /**
       * <code>string money = 2;</code>
       */
      public java.lang.String getMoney() {
        java.lang.Object ref = money_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          money_ = s;
          return s;
        }
      }
      /**
       * <code>string money = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMoneyBytes() {
        java.lang.Object ref = money_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          money_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TYPE_FIELD_NUMBER = 3;
      private int type_;
      /**
       * <code>.person.Person.PhoneType type = 3;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.person.Person.PhoneType type = 3;</code>
       */
      public com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType getType() {
        com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType result = com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType.valueOf(type_);
        return result == null ? com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (area_ != 0L) {
          output.writeInt64(1, area_);
        }
        if (!getMoneyBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, money_);
        }
        if (type_ != com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType.HOME.getNumber()) {
          output.writeEnum(3, type_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (area_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, area_);
        }
        if (!getMoneyBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, money_);
        }
        if (type_ != com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType.HOME.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, type_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.github.xjs.protobuffdemo.nano.PersonProto.Person.china)) {
          return super.equals(obj);
        }
        com.github.xjs.protobuffdemo.nano.PersonProto.Person.china other = (com.github.xjs.protobuffdemo.nano.PersonProto.Person.china) obj;

        boolean result = true;
        result = result && (getArea()
            == other.getArea());
        result = result && getMoney()
            .equals(other.getMoney());
        result = result && type_ == other.type_;
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + AREA_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getArea());
        hash = (37 * hash) + MONEY_FIELD_NUMBER;
        hash = (53 * hash) + getMoney().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.github.xjs.protobuffdemo.nano.PersonProto.Person.china prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code person.Person.china}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:person.Person.china)
          com.github.xjs.protobuffdemo.nano.PersonProto.Person.chinaOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_china_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_china_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.class, com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.Builder.class);
        }

        // Construct using com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          area_ = 0L;

          money_ = "";

          type_ = 0;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_china_descriptor;
        }

        public com.github.xjs.protobuffdemo.nano.PersonProto.Person.china getDefaultInstanceForType() {
          return com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.getDefaultInstance();
        }

        public com.github.xjs.protobuffdemo.nano.PersonProto.Person.china build() {
          com.github.xjs.protobuffdemo.nano.PersonProto.Person.china result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.github.xjs.protobuffdemo.nano.PersonProto.Person.china buildPartial() {
          com.github.xjs.protobuffdemo.nano.PersonProto.Person.china result = new com.github.xjs.protobuffdemo.nano.PersonProto.Person.china(this);
          result.area_ = area_;
          result.money_ = money_;
          result.type_ = type_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.github.xjs.protobuffdemo.nano.PersonProto.Person.china) {
            return mergeFrom((com.github.xjs.protobuffdemo.nano.PersonProto.Person.china)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.github.xjs.protobuffdemo.nano.PersonProto.Person.china other) {
          if (other == com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.getDefaultInstance()) return this;
          if (other.getArea() != 0L) {
            setArea(other.getArea());
          }
          if (!other.getMoney().isEmpty()) {
            money_ = other.money_;
            onChanged();
          }
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.github.xjs.protobuffdemo.nano.PersonProto.Person.china parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.github.xjs.protobuffdemo.nano.PersonProto.Person.china) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long area_ ;
        /**
         * <code>int64 area = 1;</code>
         */
        public long getArea() {
          return area_;
        }
        /**
         * <code>int64 area = 1;</code>
         */
        public Builder setArea(long value) {
          
          area_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 area = 1;</code>
         */
        public Builder clearArea() {
          
          area_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object money_ = "";
        /**
         * <code>string money = 2;</code>
         */
        public java.lang.String getMoney() {
          java.lang.Object ref = money_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            money_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string money = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMoneyBytes() {
          java.lang.Object ref = money_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            money_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string money = 2;</code>
         */
        public Builder setMoney(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          money_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string money = 2;</code>
         */
        public Builder clearMoney() {
          
          money_ = getDefaultInstance().getMoney();
          onChanged();
          return this;
        }
        /**
         * <code>string money = 2;</code>
         */
        public Builder setMoneyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          money_ = value;
          onChanged();
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.person.Person.PhoneType type = 3;</code>
         */
        public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.person.Person.PhoneType type = 3;</code>
         */
        public Builder setTypeValue(int value) {
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.person.Person.PhoneType type = 3;</code>
         */
        public com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType getType() {
          com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType result = com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType.valueOf(type_);
          return result == null ? com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType.UNRECOGNIZED : result;
        }
        /**
         * <code>.person.Person.PhoneType type = 3;</code>
         */
        public Builder setType(com.github.xjs.protobuffdemo.nano.PersonProto.Person.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.person.Person.PhoneType type = 3;</code>
         */
        public Builder clearType() {
          
          type_ = 0;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:person.Person.china)
      }

      // @@protoc_insertion_point(class_scope:person.Person.china)
      private static final com.github.xjs.protobuffdemo.nano.PersonProto.Person.china DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.github.xjs.protobuffdemo.nano.PersonProto.Person.china();
      }

      public static com.github.xjs.protobuffdemo.nano.PersonProto.Person.china getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<china>
          PARSER = new com.google.protobuf.AbstractParser<china>() {
        public china parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new china(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<china> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<china> getParserForType() {
        return PARSER;
      }

      public com.github.xjs.protobuffdemo.nano.PersonProto.Person.china getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int POSITION_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList position_;
    /**
     * <pre>
     *由于repeated关键字修饰，这个属性将会生成一个集合
     * </pre>
     *
     * <code>repeated string position = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPositionList() {
      return position_;
    }
    /**
     * <pre>
     *由于repeated关键字修饰，这个属性将会生成一个集合
     * </pre>
     *
     * <code>repeated string position = 7;</code>
     */
    public int getPositionCount() {
      return position_.size();
    }
    /**
     * <pre>
     *由于repeated关键字修饰，这个属性将会生成一个集合
     * </pre>
     *
     * <code>repeated string position = 7;</code>
     */
    public java.lang.String getPosition(int index) {
      return position_.get(index);
    }
    /**
     * <pre>
     *由于repeated关键字修饰，这个属性将会生成一个集合
     * </pre>
     *
     * <code>repeated string position = 7;</code>
     */
    public com.google.protobuf.ByteString
        getPositionBytes(int index) {
      return position_.getByteString(index);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NATION_FIELD_NUMBER = 5;
    private com.github.xjs.protobuffdemo.nano.PersonProto.Person.china nation_;
    /**
     * <code>.person.Person.china nation = 5;</code>
     */
    public boolean hasNation() {
      return nation_ != null;
    }
    /**
     * <code>.person.Person.china nation = 5;</code>
     */
    public com.github.xjs.protobuffdemo.nano.PersonProto.Person.china getNation() {
      return nation_ == null ? com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.getDefaultInstance() : nation_;
    }
    /**
     * <code>.person.Person.china nation = 5;</code>
     */
    public com.github.xjs.protobuffdemo.nano.PersonProto.Person.chinaOrBuilder getNationOrBuilder() {
      return getNation();
    }

    public static final int ADDRESS_FIELD_NUMBER = 8;
    private static final class AddressDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_AddressEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> address_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAddress() {
      if (address_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AddressDefaultEntryHolder.defaultEntry);
      }
      return address_;
    }

    public int getAddressCount() {
      return internalGetAddress().getMap().size();
    }
    /**
     * <pre>
     *map类型的key不能是枚举类型(enum)
     * </pre>
     *
     * <code>map&lt;string, string&gt; address = 8;</code>
     */

    public boolean containsAddress(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAddress().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAddressMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAddress() {
      return getAddressMap();
    }
    /**
     * <pre>
     *map类型的key不能是枚举类型(enum)
     * </pre>
     *
     * <code>map&lt;string, string&gt; address = 8;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAddressMap() {
      return internalGetAddress().getMap();
    }
    /**
     * <pre>
     *map类型的key不能是枚举类型(enum)
     * </pre>
     *
     * <code>map&lt;string, string&gt; address = 8;</code>
     */

    public java.lang.String getAddressOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAddress().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *map类型的key不能是枚举类型(enum)
     * </pre>
     *
     * <code>map&lt;string, string&gt; address = 8;</code>
     */

    public java.lang.String getAddressOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAddress().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int BASEPROTO_FIELD_NUMBER = 6;
    private com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData baseProto_;
    /**
     * <code>.baseproto.MsgBaseData baseProto = 6;</code>
     */
    public boolean hasBaseProto() {
      return baseProto_ != null;
    }
    /**
     * <code>.baseproto.MsgBaseData baseProto = 6;</code>
     */
    public com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData getBaseProto() {
      return baseProto_ == null ? com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.getDefaultInstance() : baseProto_;
    }
    /**
     * <code>.baseproto.MsgBaseData baseProto = 6;</code>
     */
    public com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseDataOrBuilder getBaseProtoOrBuilder() {
      return getBaseProto();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (id_ != 0) {
        output.writeInt32(3, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      if (nation_ != null) {
        output.writeMessage(5, getNation());
      }
      if (baseProto_ != null) {
        output.writeMessage(6, getBaseProto());
      }
      for (int i = 0; i < position_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, position_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAddress(),
          AddressDefaultEntryHolder.defaultEntry,
          8);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      if (nation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getNation());
      }
      if (baseProto_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getBaseProto());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < position_.size(); i++) {
          dataSize += computeStringSizeNoTag(position_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPositionList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAddress().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        address__ = AddressDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, address__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.xjs.protobuffdemo.nano.PersonProto.Person)) {
        return super.equals(obj);
      }
      com.github.xjs.protobuffdemo.nano.PersonProto.Person other = (com.github.xjs.protobuffdemo.nano.PersonProto.Person) obj;

      boolean result = true;
      result = result && getPositionList()
          .equals(other.getPositionList());
      result = result && getName()
          .equals(other.getName());
      result = result && (getAge()
          == other.getAge());
      result = result && (getId()
          == other.getId());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && (hasNation() == other.hasNation());
      if (hasNation()) {
        result = result && getNation()
            .equals(other.getNation());
      }
      result = result && internalGetAddress().equals(
          other.internalGetAddress());
      result = result && (hasBaseProto() == other.hasBaseProto());
      if (hasBaseProto()) {
        result = result && getBaseProto()
            .equals(other.getBaseProto());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPositionCount() > 0) {
        hash = (37 * hash) + POSITION_FIELD_NUMBER;
        hash = (53 * hash) + getPositionList().hashCode();
      }
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (hasNation()) {
        hash = (37 * hash) + NATION_FIELD_NUMBER;
        hash = (53 * hash) + getNation().hashCode();
      }
      if (!internalGetAddress().getMap().isEmpty()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAddress().hashCode();
      }
      if (hasBaseProto()) {
        hash = (37 * hash) + BASEPROTO_FIELD_NUMBER;
        hash = (53 * hash) + getBaseProto().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.xjs.protobuffdemo.nano.PersonProto.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *option java_multiple_files = true;
     *option java_generic_services = true;
     *option optimize_for = SPEED;
     * </pre>
     *
     * Protobuf type {@code person.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:person.Person)
        com.github.xjs.protobuffdemo.nano.PersonProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetAddress();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMutableAddress();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.xjs.protobuffdemo.nano.PersonProto.Person.class, com.github.xjs.protobuffdemo.nano.PersonProto.Person.Builder.class);
      }

      // Construct using com.github.xjs.protobuffdemo.nano.PersonProto.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        position_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";

        age_ = 0;

        id_ = 0;

        email_ = "";

        if (nationBuilder_ == null) {
          nation_ = null;
        } else {
          nation_ = null;
          nationBuilder_ = null;
        }
        internalGetMutableAddress().clear();
        if (baseProtoBuilder_ == null) {
          baseProto_ = null;
        } else {
          baseProto_ = null;
          baseProtoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.xjs.protobuffdemo.nano.PersonProto.internal_static_person_Person_descriptor;
      }

      public com.github.xjs.protobuffdemo.nano.PersonProto.Person getDefaultInstanceForType() {
        return com.github.xjs.protobuffdemo.nano.PersonProto.Person.getDefaultInstance();
      }

      public com.github.xjs.protobuffdemo.nano.PersonProto.Person build() {
        com.github.xjs.protobuffdemo.nano.PersonProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.xjs.protobuffdemo.nano.PersonProto.Person buildPartial() {
        com.github.xjs.protobuffdemo.nano.PersonProto.Person result = new com.github.xjs.protobuffdemo.nano.PersonProto.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          position_ = position_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.position_ = position_;
        result.name_ = name_;
        result.age_ = age_;
        result.id_ = id_;
        result.email_ = email_;
        if (nationBuilder_ == null) {
          result.nation_ = nation_;
        } else {
          result.nation_ = nationBuilder_.build();
        }
        result.address_ = internalGetAddress();
        result.address_.makeImmutable();
        if (baseProtoBuilder_ == null) {
          result.baseProto_ = baseProto_;
        } else {
          result.baseProto_ = baseProtoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.xjs.protobuffdemo.nano.PersonProto.Person) {
          return mergeFrom((com.github.xjs.protobuffdemo.nano.PersonProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.xjs.protobuffdemo.nano.PersonProto.Person other) {
        if (other == com.github.xjs.protobuffdemo.nano.PersonProto.Person.getDefaultInstance()) return this;
        if (!other.position_.isEmpty()) {
          if (position_.isEmpty()) {
            position_ = other.position_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePositionIsMutable();
            position_.addAll(other.position_);
          }
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.hasNation()) {
          mergeNation(other.getNation());
        }
        internalGetMutableAddress().mergeFrom(
            other.internalGetAddress());
        if (other.hasBaseProto()) {
          mergeBaseProto(other.getBaseProto());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.xjs.protobuffdemo.nano.PersonProto.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.xjs.protobuffdemo.nano.PersonProto.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList position_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePositionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          position_ = new com.google.protobuf.LazyStringArrayList(position_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *由于repeated关键字修饰，这个属性将会生成一个集合
       * </pre>
       *
       * <code>repeated string position = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPositionList() {
        return position_.getUnmodifiableView();
      }
      /**
       * <pre>
       *由于repeated关键字修饰，这个属性将会生成一个集合
       * </pre>
       *
       * <code>repeated string position = 7;</code>
       */
      public int getPositionCount() {
        return position_.size();
      }
      /**
       * <pre>
       *由于repeated关键字修饰，这个属性将会生成一个集合
       * </pre>
       *
       * <code>repeated string position = 7;</code>
       */
      public java.lang.String getPosition(int index) {
        return position_.get(index);
      }
      /**
       * <pre>
       *由于repeated关键字修饰，这个属性将会生成一个集合
       * </pre>
       *
       * <code>repeated string position = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPositionBytes(int index) {
        return position_.getByteString(index);
      }
      /**
       * <pre>
       *由于repeated关键字修饰，这个属性将会生成一个集合
       * </pre>
       *
       * <code>repeated string position = 7;</code>
       */
      public Builder setPosition(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePositionIsMutable();
        position_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *由于repeated关键字修饰，这个属性将会生成一个集合
       * </pre>
       *
       * <code>repeated string position = 7;</code>
       */
      public Builder addPosition(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePositionIsMutable();
        position_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *由于repeated关键字修饰，这个属性将会生成一个集合
       * </pre>
       *
       * <code>repeated string position = 7;</code>
       */
      public Builder addAllPosition(
          java.lang.Iterable<java.lang.String> values) {
        ensurePositionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, position_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *由于repeated关键字修饰，这个属性将会生成一个集合
       * </pre>
       *
       * <code>repeated string position = 7;</code>
       */
      public Builder clearPosition() {
        position_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *由于repeated关键字修饰，这个属性将会生成一个集合
       * </pre>
       *
       * <code>repeated string position = 7;</code>
       */
      public Builder addPositionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePositionIsMutable();
        position_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 3;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private com.github.xjs.protobuffdemo.nano.PersonProto.Person.china nation_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.xjs.protobuffdemo.nano.PersonProto.Person.china, com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.Builder, com.github.xjs.protobuffdemo.nano.PersonProto.Person.chinaOrBuilder> nationBuilder_;
      /**
       * <code>.person.Person.china nation = 5;</code>
       */
      public boolean hasNation() {
        return nationBuilder_ != null || nation_ != null;
      }
      /**
       * <code>.person.Person.china nation = 5;</code>
       */
      public com.github.xjs.protobuffdemo.nano.PersonProto.Person.china getNation() {
        if (nationBuilder_ == null) {
          return nation_ == null ? com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.getDefaultInstance() : nation_;
        } else {
          return nationBuilder_.getMessage();
        }
      }
      /**
       * <code>.person.Person.china nation = 5;</code>
       */
      public Builder setNation(com.github.xjs.protobuffdemo.nano.PersonProto.Person.china value) {
        if (nationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          nation_ = value;
          onChanged();
        } else {
          nationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.person.Person.china nation = 5;</code>
       */
      public Builder setNation(
          com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.Builder builderForValue) {
        if (nationBuilder_ == null) {
          nation_ = builderForValue.build();
          onChanged();
        } else {
          nationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.person.Person.china nation = 5;</code>
       */
      public Builder mergeNation(com.github.xjs.protobuffdemo.nano.PersonProto.Person.china value) {
        if (nationBuilder_ == null) {
          if (nation_ != null) {
            nation_ =
              com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.newBuilder(nation_).mergeFrom(value).buildPartial();
          } else {
            nation_ = value;
          }
          onChanged();
        } else {
          nationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.person.Person.china nation = 5;</code>
       */
      public Builder clearNation() {
        if (nationBuilder_ == null) {
          nation_ = null;
          onChanged();
        } else {
          nation_ = null;
          nationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.person.Person.china nation = 5;</code>
       */
      public com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.Builder getNationBuilder() {
        
        onChanged();
        return getNationFieldBuilder().getBuilder();
      }
      /**
       * <code>.person.Person.china nation = 5;</code>
       */
      public com.github.xjs.protobuffdemo.nano.PersonProto.Person.chinaOrBuilder getNationOrBuilder() {
        if (nationBuilder_ != null) {
          return nationBuilder_.getMessageOrBuilder();
        } else {
          return nation_ == null ?
              com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.getDefaultInstance() : nation_;
        }
      }
      /**
       * <code>.person.Person.china nation = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.xjs.protobuffdemo.nano.PersonProto.Person.china, com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.Builder, com.github.xjs.protobuffdemo.nano.PersonProto.Person.chinaOrBuilder> 
          getNationFieldBuilder() {
        if (nationBuilder_ == null) {
          nationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.xjs.protobuffdemo.nano.PersonProto.Person.china, com.github.xjs.protobuffdemo.nano.PersonProto.Person.china.Builder, com.github.xjs.protobuffdemo.nano.PersonProto.Person.chinaOrBuilder>(
                  getNation(),
                  getParentForChildren(),
                  isClean());
          nation_ = null;
        }
        return nationBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> address_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAddress() {
        if (address_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AddressDefaultEntryHolder.defaultEntry);
        }
        return address_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAddress() {
        onChanged();;
        if (address_ == null) {
          address_ = com.google.protobuf.MapField.newMapField(
              AddressDefaultEntryHolder.defaultEntry);
        }
        if (!address_.isMutable()) {
          address_ = address_.copy();
        }
        return address_;
      }

      public int getAddressCount() {
        return internalGetAddress().getMap().size();
      }
      /**
       * <pre>
       *map类型的key不能是枚举类型(enum)
       * </pre>
       *
       * <code>map&lt;string, string&gt; address = 8;</code>
       */

      public boolean containsAddress(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAddress().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAddressMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAddress() {
        return getAddressMap();
      }
      /**
       * <pre>
       *map类型的key不能是枚举类型(enum)
       * </pre>
       *
       * <code>map&lt;string, string&gt; address = 8;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAddressMap() {
        return internalGetAddress().getMap();
      }
      /**
       * <pre>
       *map类型的key不能是枚举类型(enum)
       * </pre>
       *
       * <code>map&lt;string, string&gt; address = 8;</code>
       */

      public java.lang.String getAddressOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAddress().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *map类型的key不能是枚举类型(enum)
       * </pre>
       *
       * <code>map&lt;string, string&gt; address = 8;</code>
       */

      public java.lang.String getAddressOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAddress().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAddress() {
        internalGetMutableAddress().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *map类型的key不能是枚举类型(enum)
       * </pre>
       *
       * <code>map&lt;string, string&gt; address = 8;</code>
       */

      public Builder removeAddress(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAddress().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAddress() {
        return internalGetMutableAddress().getMutableMap();
      }
      /**
       * <pre>
       *map类型的key不能是枚举类型(enum)
       * </pre>
       *
       * <code>map&lt;string, string&gt; address = 8;</code>
       */
      public Builder putAddress(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAddress().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *map类型的key不能是枚举类型(enum)
       * </pre>
       *
       * <code>map&lt;string, string&gt; address = 8;</code>
       */

      public Builder putAllAddress(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAddress().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData baseProto_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData, com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.Builder, com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseDataOrBuilder> baseProtoBuilder_;
      /**
       * <code>.baseproto.MsgBaseData baseProto = 6;</code>
       */
      public boolean hasBaseProto() {
        return baseProtoBuilder_ != null || baseProto_ != null;
      }
      /**
       * <code>.baseproto.MsgBaseData baseProto = 6;</code>
       */
      public com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData getBaseProto() {
        if (baseProtoBuilder_ == null) {
          return baseProto_ == null ? com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.getDefaultInstance() : baseProto_;
        } else {
          return baseProtoBuilder_.getMessage();
        }
      }
      /**
       * <code>.baseproto.MsgBaseData baseProto = 6;</code>
       */
      public Builder setBaseProto(com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData value) {
        if (baseProtoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseProto_ = value;
          onChanged();
        } else {
          baseProtoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.baseproto.MsgBaseData baseProto = 6;</code>
       */
      public Builder setBaseProto(
          com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.Builder builderForValue) {
        if (baseProtoBuilder_ == null) {
          baseProto_ = builderForValue.build();
          onChanged();
        } else {
          baseProtoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.baseproto.MsgBaseData baseProto = 6;</code>
       */
      public Builder mergeBaseProto(com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData value) {
        if (baseProtoBuilder_ == null) {
          if (baseProto_ != null) {
            baseProto_ =
              com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.newBuilder(baseProto_).mergeFrom(value).buildPartial();
          } else {
            baseProto_ = value;
          }
          onChanged();
        } else {
          baseProtoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.baseproto.MsgBaseData baseProto = 6;</code>
       */
      public Builder clearBaseProto() {
        if (baseProtoBuilder_ == null) {
          baseProto_ = null;
          onChanged();
        } else {
          baseProto_ = null;
          baseProtoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.baseproto.MsgBaseData baseProto = 6;</code>
       */
      public com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.Builder getBaseProtoBuilder() {
        
        onChanged();
        return getBaseProtoFieldBuilder().getBuilder();
      }
      /**
       * <code>.baseproto.MsgBaseData baseProto = 6;</code>
       */
      public com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseDataOrBuilder getBaseProtoOrBuilder() {
        if (baseProtoBuilder_ != null) {
          return baseProtoBuilder_.getMessageOrBuilder();
        } else {
          return baseProto_ == null ?
              com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.getDefaultInstance() : baseProto_;
        }
      }
      /**
       * <code>.baseproto.MsgBaseData baseProto = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData, com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.Builder, com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseDataOrBuilder> 
          getBaseProtoFieldBuilder() {
        if (baseProtoBuilder_ == null) {
          baseProtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData, com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseData.Builder, com.github.xjs.protobuffdemo.nano.BaseProto.MsgBaseDataOrBuilder>(
                  getBaseProto(),
                  getParentForChildren(),
                  isClean());
          baseProto_ = null;
        }
        return baseProtoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:person.Person)
    }

    // @@protoc_insertion_point(class_scope:person.Person)
    private static final com.github.xjs.protobuffdemo.nano.PersonProto.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.xjs.protobuffdemo.nano.PersonProto.Person();
    }

    public static com.github.xjs.protobuffdemo.nano.PersonProto.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    public com.github.xjs.protobuffdemo.nano.PersonProto.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_Person_china_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_Person_china_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_person_Person_AddressEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_person_Person_AddressEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Person.proto\022\006person\032\017BaseProto.proto\"" +
      "\213\003\n\006Person\022\020\n\010position\030\007 \003(\t\022\014\n\004name\030\001 \001" +
      "(\t\022\013\n\003age\030\002 \001(\005\022\n\n\002id\030\003 \001(\005\022\r\n\005email\030\004 \001" +
      "(\t\022$\n\006nation\030\005 \001(\0132\024.person.Person.china" +
      "\022,\n\007address\030\010 \003(\0132\033.person.Person.Addres" +
      "sEntry\022)\n\tbaseProto\030\006 \001(\0132\026.baseproto.Ms" +
      "gBaseData\032L\n\005china\022\014\n\004area\030\001 \001(\003\022\r\n\005mone" +
      "y\030\002 \001(\t\022&\n\004type\030\003 \001(\0162\030.person.Person.Ph" +
      "oneType\032.\n\014AddressEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001\"<\n\tPhoneType\022\010\n\004HOME\020\000\022\n" +
      "\n\006MOBILE\020\001\022\010\n\004WORK\020\002\022\013\n\007COMPANY\020\002\032\002\020\001B0\n" +
      "!com.github.xjs.protobuffdemo.nanoB\013Pers" +
      "onProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.xjs.protobuffdemo.nano.BaseProto.getDescriptor(),
        }, assigner);
    internal_static_person_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_person_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_Person_descriptor,
        new java.lang.String[] { "Position", "Name", "Age", "Id", "Email", "Nation", "Address", "BaseProto", });
    internal_static_person_Person_china_descriptor =
      internal_static_person_Person_descriptor.getNestedTypes().get(0);
    internal_static_person_Person_china_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_Person_china_descriptor,
        new java.lang.String[] { "Area", "Money", "Type", });
    internal_static_person_Person_AddressEntry_descriptor =
      internal_static_person_Person_descriptor.getNestedTypes().get(1);
    internal_static_person_Person_AddressEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_person_Person_AddressEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.github.xjs.protobuffdemo.nano.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
