// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerProto.proto

package com.github.xjs.protobuffdemo.nano;

public final class ServerProto {
  private ServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServerWeaponDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServerProto.proto.ServerWeaponData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string guid = 1;</code>
     */
    java.lang.String getGuid();
    /**
     * <code>string guid = 1;</code>
     */
    com.google.protobuf.ByteString
        getGuidBytes();

    /**
     * <code>int32 playerID = 2;</code>
     */
    int getPlayerID();

    /**
     * <code>string accountName = 3;</code>
     */
    java.lang.String getAccountName();
    /**
     * <code>string accountName = 3;</code>
     */
    com.google.protobuf.ByteString
        getAccountNameBytes();

    /**
     * <code>int32 weaponID = 4;</code>
     */
    int getWeaponID();

    /**
     * <code>int32 weaponLv = 5;</code>
     */
    int getWeaponLv();

    /**
     * <code>int32 slotID = 6;</code>
     */
    int getSlotID();

    /**
     * <pre>
     * 需要加上包名GameProto
     * </pre>
     *
     * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
     */
    boolean hasSkillData();
    /**
     * <pre>
     * 需要加上包名GameProto
     * </pre>
     *
     * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
     */
    com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData getSkillData();
    /**
     * <pre>
     * 需要加上包名GameProto
     * </pre>
     *
     * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
     */
    com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillDataOrBuilder getSkillDataOrBuilder();
  }
  /**
   * Protobuf type {@code ServerProto.proto.ServerWeaponData}
   */
  public  static final class ServerWeaponData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServerProto.proto.ServerWeaponData)
      ServerWeaponDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServerWeaponData.newBuilder() to construct.
    private ServerWeaponData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServerWeaponData() {
      guid_ = "";
      playerID_ = 0;
      accountName_ = "";
      weaponID_ = 0;
      weaponLv_ = 0;
      slotID_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServerWeaponData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              guid_ = s;
              break;
            }
            case 16: {

              playerID_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              accountName_ = s;
              break;
            }
            case 32: {

              weaponID_ = input.readInt32();
              break;
            }
            case 40: {

              weaponLv_ = input.readInt32();
              break;
            }
            case 48: {

              slotID_ = input.readInt32();
              break;
            }
            case 58: {
              com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.Builder subBuilder = null;
              if (skillData_ != null) {
                subBuilder = skillData_.toBuilder();
              }
              skillData_ = input.readMessage(com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(skillData_);
                skillData_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.xjs.protobuffdemo.nano.ServerProto.internal_static_ServerProto_proto_ServerWeaponData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.xjs.protobuffdemo.nano.ServerProto.internal_static_ServerProto_proto_ServerWeaponData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData.class, com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData.Builder.class);
    }

    public static final int GUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object guid_;
    /**
     * <code>string guid = 1;</code>
     */
    public java.lang.String getGuid() {
      java.lang.Object ref = guid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        guid_ = s;
        return s;
      }
    }
    /**
     * <code>string guid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGuidBytes() {
      java.lang.Object ref = guid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        guid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERID_FIELD_NUMBER = 2;
    private int playerID_;
    /**
     * <code>int32 playerID = 2;</code>
     */
    public int getPlayerID() {
      return playerID_;
    }

    public static final int ACCOUNTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object accountName_;
    /**
     * <code>string accountName = 3;</code>
     */
    public java.lang.String getAccountName() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountName_ = s;
        return s;
      }
    }
    /**
     * <code>string accountName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNameBytes() {
      java.lang.Object ref = accountName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEAPONID_FIELD_NUMBER = 4;
    private int weaponID_;
    /**
     * <code>int32 weaponID = 4;</code>
     */
    public int getWeaponID() {
      return weaponID_;
    }

    public static final int WEAPONLV_FIELD_NUMBER = 5;
    private int weaponLv_;
    /**
     * <code>int32 weaponLv = 5;</code>
     */
    public int getWeaponLv() {
      return weaponLv_;
    }

    public static final int SLOTID_FIELD_NUMBER = 6;
    private int slotID_;
    /**
     * <code>int32 slotID = 6;</code>
     */
    public int getSlotID() {
      return slotID_;
    }

    public static final int SKILLDATA_FIELD_NUMBER = 7;
    private com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData skillData_;
    /**
     * <pre>
     * 需要加上包名GameProto
     * </pre>
     *
     * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
     */
    public boolean hasSkillData() {
      return skillData_ != null;
    }
    /**
     * <pre>
     * 需要加上包名GameProto
     * </pre>
     *
     * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
     */
    public com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData getSkillData() {
      return skillData_ == null ? com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.getDefaultInstance() : skillData_;
    }
    /**
     * <pre>
     * 需要加上包名GameProto
     * </pre>
     *
     * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
     */
    public com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillDataOrBuilder getSkillDataOrBuilder() {
      return getSkillData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, guid_);
      }
      if (playerID_ != 0) {
        output.writeInt32(2, playerID_);
      }
      if (!getAccountNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, accountName_);
      }
      if (weaponID_ != 0) {
        output.writeInt32(4, weaponID_);
      }
      if (weaponLv_ != 0) {
        output.writeInt32(5, weaponLv_);
      }
      if (slotID_ != 0) {
        output.writeInt32(6, slotID_);
      }
      if (skillData_ != null) {
        output.writeMessage(7, getSkillData());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, guid_);
      }
      if (playerID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, playerID_);
      }
      if (!getAccountNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, accountName_);
      }
      if (weaponID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, weaponID_);
      }
      if (weaponLv_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, weaponLv_);
      }
      if (slotID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, slotID_);
      }
      if (skillData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getSkillData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData)) {
        return super.equals(obj);
      }
      com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData other = (com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData) obj;

      boolean result = true;
      result = result && getGuid()
          .equals(other.getGuid());
      result = result && (getPlayerID()
          == other.getPlayerID());
      result = result && getAccountName()
          .equals(other.getAccountName());
      result = result && (getWeaponID()
          == other.getWeaponID());
      result = result && (getWeaponLv()
          == other.getWeaponLv());
      result = result && (getSlotID()
          == other.getSlotID());
      result = result && (hasSkillData() == other.hasSkillData());
      if (hasSkillData()) {
        result = result && getSkillData()
            .equals(other.getSkillData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GUID_FIELD_NUMBER;
      hash = (53 * hash) + getGuid().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerID();
      hash = (37 * hash) + ACCOUNTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getAccountName().hashCode();
      hash = (37 * hash) + WEAPONID_FIELD_NUMBER;
      hash = (53 * hash) + getWeaponID();
      hash = (37 * hash) + WEAPONLV_FIELD_NUMBER;
      hash = (53 * hash) + getWeaponLv();
      hash = (37 * hash) + SLOTID_FIELD_NUMBER;
      hash = (53 * hash) + getSlotID();
      if (hasSkillData()) {
        hash = (37 * hash) + SKILLDATA_FIELD_NUMBER;
        hash = (53 * hash) + getSkillData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServerProto.proto.ServerWeaponData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServerProto.proto.ServerWeaponData)
        com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.xjs.protobuffdemo.nano.ServerProto.internal_static_ServerProto_proto_ServerWeaponData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.xjs.protobuffdemo.nano.ServerProto.internal_static_ServerProto_proto_ServerWeaponData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData.class, com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData.Builder.class);
      }

      // Construct using com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        guid_ = "";

        playerID_ = 0;

        accountName_ = "";

        weaponID_ = 0;

        weaponLv_ = 0;

        slotID_ = 0;

        if (skillDataBuilder_ == null) {
          skillData_ = null;
        } else {
          skillData_ = null;
          skillDataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.xjs.protobuffdemo.nano.ServerProto.internal_static_ServerProto_proto_ServerWeaponData_descriptor;
      }

      public com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData getDefaultInstanceForType() {
        return com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData.getDefaultInstance();
      }

      public com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData build() {
        com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData buildPartial() {
        com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData result = new com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData(this);
        result.guid_ = guid_;
        result.playerID_ = playerID_;
        result.accountName_ = accountName_;
        result.weaponID_ = weaponID_;
        result.weaponLv_ = weaponLv_;
        result.slotID_ = slotID_;
        if (skillDataBuilder_ == null) {
          result.skillData_ = skillData_;
        } else {
          result.skillData_ = skillDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData) {
          return mergeFrom((com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData other) {
        if (other == com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData.getDefaultInstance()) return this;
        if (!other.getGuid().isEmpty()) {
          guid_ = other.guid_;
          onChanged();
        }
        if (other.getPlayerID() != 0) {
          setPlayerID(other.getPlayerID());
        }
        if (!other.getAccountName().isEmpty()) {
          accountName_ = other.accountName_;
          onChanged();
        }
        if (other.getWeaponID() != 0) {
          setWeaponID(other.getWeaponID());
        }
        if (other.getWeaponLv() != 0) {
          setWeaponLv(other.getWeaponLv());
        }
        if (other.getSlotID() != 0) {
          setSlotID(other.getSlotID());
        }
        if (other.hasSkillData()) {
          mergeSkillData(other.getSkillData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object guid_ = "";
      /**
       * <code>string guid = 1;</code>
       */
      public java.lang.String getGuid() {
        java.lang.Object ref = guid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          guid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string guid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGuidBytes() {
        java.lang.Object ref = guid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          guid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string guid = 1;</code>
       */
      public Builder setGuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        guid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string guid = 1;</code>
       */
      public Builder clearGuid() {
        
        guid_ = getDefaultInstance().getGuid();
        onChanged();
        return this;
      }
      /**
       * <code>string guid = 1;</code>
       */
      public Builder setGuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        guid_ = value;
        onChanged();
        return this;
      }

      private int playerID_ ;
      /**
       * <code>int32 playerID = 2;</code>
       */
      public int getPlayerID() {
        return playerID_;
      }
      /**
       * <code>int32 playerID = 2;</code>
       */
      public Builder setPlayerID(int value) {
        
        playerID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 playerID = 2;</code>
       */
      public Builder clearPlayerID() {
        
        playerID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object accountName_ = "";
      /**
       * <code>string accountName = 3;</code>
       */
      public java.lang.String getAccountName() {
        java.lang.Object ref = accountName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accountName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string accountName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAccountNameBytes() {
        java.lang.Object ref = accountName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accountName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string accountName = 3;</code>
       */
      public Builder setAccountName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accountName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string accountName = 3;</code>
       */
      public Builder clearAccountName() {
        
        accountName_ = getDefaultInstance().getAccountName();
        onChanged();
        return this;
      }
      /**
       * <code>string accountName = 3;</code>
       */
      public Builder setAccountNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accountName_ = value;
        onChanged();
        return this;
      }

      private int weaponID_ ;
      /**
       * <code>int32 weaponID = 4;</code>
       */
      public int getWeaponID() {
        return weaponID_;
      }
      /**
       * <code>int32 weaponID = 4;</code>
       */
      public Builder setWeaponID(int value) {
        
        weaponID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 weaponID = 4;</code>
       */
      public Builder clearWeaponID() {
        
        weaponID_ = 0;
        onChanged();
        return this;
      }

      private int weaponLv_ ;
      /**
       * <code>int32 weaponLv = 5;</code>
       */
      public int getWeaponLv() {
        return weaponLv_;
      }
      /**
       * <code>int32 weaponLv = 5;</code>
       */
      public Builder setWeaponLv(int value) {
        
        weaponLv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 weaponLv = 5;</code>
       */
      public Builder clearWeaponLv() {
        
        weaponLv_ = 0;
        onChanged();
        return this;
      }

      private int slotID_ ;
      /**
       * <code>int32 slotID = 6;</code>
       */
      public int getSlotID() {
        return slotID_;
      }
      /**
       * <code>int32 slotID = 6;</code>
       */
      public Builder setSlotID(int value) {
        
        slotID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 slotID = 6;</code>
       */
      public Builder clearSlotID() {
        
        slotID_ = 0;
        onChanged();
        return this;
      }

      private com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData skillData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData, com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.Builder, com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillDataOrBuilder> skillDataBuilder_;
      /**
       * <pre>
       * 需要加上包名GameProto
       * </pre>
       *
       * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
       */
      public boolean hasSkillData() {
        return skillDataBuilder_ != null || skillData_ != null;
      }
      /**
       * <pre>
       * 需要加上包名GameProto
       * </pre>
       *
       * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
       */
      public com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData getSkillData() {
        if (skillDataBuilder_ == null) {
          return skillData_ == null ? com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.getDefaultInstance() : skillData_;
        } else {
          return skillDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 需要加上包名GameProto
       * </pre>
       *
       * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
       */
      public Builder setSkillData(com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData value) {
        if (skillDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          skillData_ = value;
          onChanged();
        } else {
          skillDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 需要加上包名GameProto
       * </pre>
       *
       * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
       */
      public Builder setSkillData(
          com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.Builder builderForValue) {
        if (skillDataBuilder_ == null) {
          skillData_ = builderForValue.build();
          onChanged();
        } else {
          skillDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 需要加上包名GameProto
       * </pre>
       *
       * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
       */
      public Builder mergeSkillData(com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData value) {
        if (skillDataBuilder_ == null) {
          if (skillData_ != null) {
            skillData_ =
              com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.newBuilder(skillData_).mergeFrom(value).buildPartial();
          } else {
            skillData_ = value;
          }
          onChanged();
        } else {
          skillDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 需要加上包名GameProto
       * </pre>
       *
       * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
       */
      public Builder clearSkillData() {
        if (skillDataBuilder_ == null) {
          skillData_ = null;
          onChanged();
        } else {
          skillData_ = null;
          skillDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 需要加上包名GameProto
       * </pre>
       *
       * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
       */
      public com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.Builder getSkillDataBuilder() {
        
        onChanged();
        return getSkillDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 需要加上包名GameProto
       * </pre>
       *
       * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
       */
      public com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillDataOrBuilder getSkillDataOrBuilder() {
        if (skillDataBuilder_ != null) {
          return skillDataBuilder_.getMessageOrBuilder();
        } else {
          return skillData_ == null ?
              com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.getDefaultInstance() : skillData_;
        }
      }
      /**
       * <pre>
       * 需要加上包名GameProto
       * </pre>
       *
       * <code>.GameProto.MsgWeaponSkillData skillData = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData, com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.Builder, com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillDataOrBuilder> 
          getSkillDataFieldBuilder() {
        if (skillDataBuilder_ == null) {
          skillDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData, com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillData.Builder, com.github.xjs.protobuffdemo.nano.MessageProto.MsgWeaponSkillDataOrBuilder>(
                  getSkillData(),
                  getParentForChildren(),
                  isClean());
          skillData_ = null;
        }
        return skillDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ServerProto.proto.ServerWeaponData)
    }

    // @@protoc_insertion_point(class_scope:ServerProto.proto.ServerWeaponData)
    private static final com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData();
    }

    public static com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServerWeaponData>
        PARSER = new com.google.protobuf.AbstractParser<ServerWeaponData>() {
      public ServerWeaponData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerWeaponData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServerWeaponData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServerWeaponData> getParserForType() {
      return PARSER;
    }

    public com.github.xjs.protobuffdemo.nano.ServerProto.ServerWeaponData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServerProto_proto_ServerWeaponData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServerProto_proto_ServerWeaponData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ServerProto.proto\022\021ServerProto.proto\032\022" +
      "MessageProto.proto\"\255\001\n\020ServerWeaponData\022" +
      "\014\n\004guid\030\001 \001(\t\022\020\n\010playerID\030\002 \001(\005\022\023\n\013accou" +
      "ntName\030\003 \001(\t\022\020\n\010weaponID\030\004 \001(\005\022\020\n\010weapon" +
      "Lv\030\005 \001(\005\022\016\n\006slotID\030\006 \001(\005\0220\n\tskillData\030\007 " +
      "\001(\0132\035.GameProto.MsgWeaponSkillDataB0\n!co" +
      "m.github.xjs.protobuffdemo.nanoB\013ServerP" +
      "rotoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.xjs.protobuffdemo.nano.MessageProto.getDescriptor(),
        }, assigner);
    internal_static_ServerProto_proto_ServerWeaponData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServerProto_proto_ServerWeaponData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServerProto_proto_ServerWeaponData_descriptor,
        new java.lang.String[] { "Guid", "PlayerID", "AccountName", "WeaponID", "WeaponLv", "SlotID", "SkillData", });
    com.github.xjs.protobuffdemo.nano.MessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
